version: "3.9"
services:
  local-postgres:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=esdras_db
